# Generated by Django 5.0.3 on 2026-06-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='Сотрудник', max_length=255, verbose_name='ФИО'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(default='Сотрудник', max_length=100, verbose_name='Должность'),
            preserve_default=False,
        ),
    ]
